### PR TITLE
Add capability to add cover image from file systerm

### PR DESCRIPTION
**Pull request by alilotfi**
This commit:
- [X] Renames "Cover" to "Cover from internet"
- [x] Adds "Cover from file system" option
- [X] Allows user to pick an image, then crop it and assign it to Audiobook

(According to approved feature #301)

### CODE REVIEW

**Comment by PaulWoitaschek** [comment]
Thanks very much! Unfortunately there were some breaking changes in the mean time.

This could be implemented from the `BookShelfController` class. Controllers also have an `onActivityResult`.
* If you change language keys please change the english translations only. The others translations will be synced through Transifex.
* The Crop intent is not reliable to be available on each device. Also it can not guarantee to be square.
* In previous versions of this app there was a dialog which was able to handle cover cropping, this could be used. -> [Latest version](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/1a4dc61f7ef75aa6579fff8567653a6768208778/audiobook/src/main/kotlin/de/ph1b/audiobook/dialog/EditCoverDialogFragment.kt)

**Comment by alilotfi** [comment]
Thank you very much for your tips.
About `BookShelfController`, do you mean `BookShelfPresenter`? Or I have to write the controller myself and delegate `Activity`'s `onActivityResult` to it?

**Comment by PaulWoitaschek** [comment]
I mean [BookShelfController.kt](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/develop/audiobook/src/main/java/de/ph1b/audiobook/features/book_overview/BookShelfController.kt)

**Comment by alilotfi** [comment]
Because calling `show()` will raise:
`java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState`
The reason is that, when we show the menu dialog to user, activity saves it's instance before being paused, so before resuming again, we cannot attach a fragment to it.

**Comment by PaulWoitaschek** [comment]
Thanks 👍

**Pull request merged**
