### PR TITLE
Control Media Broadcasts

### PR DESCRIPTION
**Pull request by HumbleBeeBumbleBee**
Control Media Broadcasts with MaterialAudiobookPlayer or Simple Last.fm
Scrobbler.

### CODE REVIEW

**Comment by PaulWoitaschek** [comment]
Can you describe why you added a setting for that?
If I understand correctly the only missing part was the package name?

**Comment by HumbleBeeBumbleBee** [comment]
A user requested this feature. I added both so the user would have redundancy. This allows you to choose either method. It is correct however that for SLS only package name is required.

**Comment by HumbleBeeBumbleBee** [comment]
Other scrobblers may not have this functionality.

**Comment by PaulWoitaschek** [comment]
Which functionality?

**Comment by HumbleBeeBumbleBee** [comment]
Disabling applications. An example is the official Last.fm scrobbler.

**Comment by PaulWoitaschek** [comment]
Thanks for the pull request. I prefer not to have an additional setting.

**Pull request closed without merging**
