### PR TITLE
fix build issues from command line

### PR DESCRIPTION
**Pull request by Eifelschaf**
This fixes two issues when building form command line. FOr some reason the "all" argument made the ndk compiler crash, but just putting all supported architectures in fixed that.

### CODE REVIEW

**Comment by Eifelschaf** [comment]
OK. I guess 60 seconds may mot be enough to build everything on the remote server?

**Comment by PaulWoitaschek** [comment]
Feel free to remove the timeout parameter at all for all calls. I guess CI will time out itself.

**Comment by Eifelschaf** [comment]
looks like the timeout is needed after all (or the flac compilation fails), but now it looks like some test is stuck.

**Comment by PaulWoitaschek** [comment]
You can remove the timeout but leave the waitFor

**Comment by Eifelschaf** [comment]
I see my fault :) I'll update the code again.

**Comment by PaulWoitaschek** [comment]
Thanks :)

**Pull request merged**
