### PR TITLE
Preference for toggling cover art on lockscreen

### PR DESCRIPTION
**Pull request by nioncode**
As discussed in #486, some people prefer to not get their wallpaper replaced by an audiobook's cover.

For example, I have carefully selected a couple of my photos that look great as wallpapers.
However, I rarely get to see them, because I often have MaterialAudiobookPlayer running.
99% of the cover art of my audiobooks is simply boring, though. Most of the time, it's just the book title printed in a fancy way, which does not look good at all.

### CODE REVIEW

**Comment by PaulWoitaschek** [comment]
My intent was to check for the quality of the artwork, not to add an additional preference.

**Comment by nioncode** [comment]
Currently, there are two problems:
1. Bad quality artwork: this looks ugly, no matter what your taste is. That's why you proposed to check for the quality and show a default cover or something if the quality is not good enough.

2. Simply ugly artwork: this has a good enough resolution, but the picture itself is simply not nice to look at, especially compared to beautiful wallpapers that are chosen explicitly for that purpose. I (and others in the linked issue thread) do not want to see their wallpaper replaced at all. That's what this PR tackles.

Could you please reconsider merging this? I'd like to avoid managing my own fork just for this single feature.

**Comment by PaulWoitaschek** [comment]
In the case that the cover does not look good I suggest finding a better one. You can use the cover picker and use any image from the internet you like.

As much as I appreciate pull requests I think this is a rather edge case I don't want to confuse anyone with.

**Comment by ypid** [comment]
I would find it useful. Thanks to @nioncode for the PR :+1:

Maybe a expert/advanced settings toggle preference could be used to hide such settings which might "confuse" people. This is done in many applications/appliances/whatever to make all of the users happy :wink: @PaulWoitaschek Would that be an option?

**Pull request closed without merging**
